name: Deploy Astro to AWS

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and build
      run: |
        npm install
        npm run build  # replace with your build command if different
